definitions:
  auth.OTPVerificationRequest:
    properties:
      email:
        type: string
      otp:
        type: integer
    required:
    - email
    - otp
    type: object
  auth.RegisterResponse:
    properties:
      data:
        $ref: '#/definitions/auth.RegisterResponseData'
      er:
        type: string
      message:
        type: string
      statusCode:
        type: integer
    type: object
  auth.RegisterResponseData:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - multipart/form-data
      - application/json
      description: Register a new user
      parameters:
      - description: Username
        in: formData
        name: name
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: Register a new user
      tags:
      - auth
  /auth/verify:
    post:
      consumes:
      - application/json
      description: OTP authentication
      parameters:
      - description: OTP Verification Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.OTPVerificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
      summary: OTP authentication
      tags:
      - auth
swagger: "2.0"
